apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixgyohn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ixgyohn
  template:
    metadata:
      labels:
        app: ixgyohn
    spec:
      containers:
        - name: ixgyohn
          image: ixgyohn
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1323
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
          env:
            - name: REDIS_URL
              value: "redis://localhost:6379"
            - name: IMGPROXY_URL
              value: "https://imgproxy.otomadb.com"
            - name: IMGPROXY_KEY
              valueFrom:
                secretKeyRef:
                  name: ixgyohn-secret
                  key: imgproxyKey
            - name: IMGPROXY_SALT
              valueFrom:
                secretKeyRef:
                  name: ixgyohn-secret
                  key: imgproxySalt
        - name: redis
          image: redis:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "1"
              memory: "128Mi"
