apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_graphiql="false"
images:
- name: api
  newName: ghcr.io/otomadb/api
  digest: sha256:802cb99931e3ee94c31a60bb8d4647f47d21282bf28bac471b0aa7030bfff3b2
- name: api-postgres-migration
  newName: ghcr.io/otomadb/api-postgres-migration
  newTag: 1bb0829ef0a2928f4ff56ac948c7963e3d79b078
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
