apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod-otomadb
commonLabels:
  app.kubernetes.io/env: prod
  app.kubernetes.io/managed-by: kustomize
generators:
- ./secret-generator.yaml
bases:
- ../../base
resources:
- ./ingress.yaml
configMapGenerator:
- name: api-configmap
  behavior: merge
  literals:
  - enable_samesite_none="false"
  - enable_graphiql="true"
images:
- name: api
  newName: ghcr.io/otomad-database/api
  digest: sha256:f21bbf911e2d15d7034a84c62d8e85e483b8a39dbe66f2aa88073035c1d0f7e7
- name: api-postgres-migration
  newName: ghcr.io/otomad-database/api-postgres-migration
  newTag: 1bb0829ef0a2928f4ff56ac948c7963e3d79b078
