apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
images:
- name: ixgyohn
  newName: ghcr.io/otomadb/ixgyohn
  digest: sha256:4d76bead1eaf5d668dd61a29d5ce19914503401df731952000aa2e1c3822885b
