apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../
  - ./ingress.yaml
  - ./secrets.enc.yaml
images:
  - digest: sha256:04c97ce4687f05584028349b9433e834407b755607799af7dd79e42afd4f93da
    name: ixgyohn
    newName: ghcr.io/otomadb/ixgyohn
