apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
configMapGenerator:
- behavior: merge
  literals:
  - enable_graphiql="false"
  - ixgyohn.baseUrl="https://images.otomadb.com"
  name: api-configmap
images:
- name: api
  newName: ghcr.io/otomadb/api
  digest: sha256:35b5bc1c3f70c2818cecd202eed9b301bdfa6a700cdb8e6250b9ad180820ea52
- name: api-postgres-migration
  newName: ghcr.io/otomadb/api-postgres-migration
  newTag: 20231214201404_nicovideo_video_source_registeredat
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/env: prod
    app.kubernetes.io/managed-by: kustomize
