apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
configMapGenerator:
- behavior: merge
  literals:
  - enable_graphiql="false"
  - enable_graphql_introspection="true"
  name: api-configmap
images:
- name: graphql-api
  newName: ghcr.io/otomadb/graphql-api
  digest: sha256:465e12db87c665a7c422a321ef1ca78424a7f4e2e78076710bf72860a7a072a9
- name: postgres-migration
  newName: ghcr.io/otomadb/postgres-migration
  newTag: 20231216122702_is_original
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
- name: nicovideo-updater
  newName: ghcr.io/otomadb/nicovideo-updater
  digest: sha256:567e4a1d497681ca062a1fd21b22309f049e6c7615f1f0424d1762434d411c4f
- name: ixgyohn
  newName: ghcr.io/otomadb/ixgyohn
  digest: sha256:8e16e79209b2d037fbdaef11cb963238806794709660587ec4faa4ae6ae36872
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/env: prod
    app.kubernetes.io/managed-by: kustomize
