apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
configMapGenerator:
- behavior: merge
  literals:
  - enable_graphiql="false"
  - enable_graphql_introspection="true"
  name: api-configmap
images:
- name: graphql-api
  newName: ghcr.io/otomadb/graphql-api
  digest: sha256:f7a62eb3425e3657c4b18c059bdfcedd063da02bd5b93df92bfc2bac00a970c3
- name: postgres-migration
  newName: ghcr.io/otomadb/postgres-migration
  newTag: 20231216122702_is_original
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
- name: nicovideo-updater
  newName: ghcr.io/otomadb/nicovideo-updater
  digest: sha256:f65b79a038cf695a42e637db23108652a08f256338e0f49fd7932ee6d700735c
- name: ixgyohn
  newName: ghcr.io/otomadb/ixgyohn
  digest: sha256:1baaeffda499b5ec03d281360cc8e89c4738d2525559a3ea800e7c9cb2eb4d85
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/env: prod
    app.kubernetes.io/managed-by: kustomize
