apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
configMapGenerator:
- behavior: merge
  literals:
  - enable_graphiql="false"
  - enable_graphql_introspection="true"
  - ixgyohn.baseUrl="https://images.otomadb.com"
  name: api-configmap
images:
- name: graphql-api
  newName: ghcr.io/otomadb/graphql-api
  digest: sha256:099e7ad7087d14e229a5a1caa479d1b7b8439a0f7131d9bcb8066c4bd35fc453
- name: postgres-migration
  newName: ghcr.io/otomadb/postgres-migration
  newTag: 20231216122702_is_original
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
- name: nicovideo-updater
  newName: ghcr.io/otomadb/nicovideo-updater
  digest: sha256:e77ae2cfc6dbff1f0229d38977f861949f6ec2666c7aad50a8f34b76b0b668d7
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/env: prod
    app.kubernetes.io/managed-by: kustomize
