apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
configMapGenerator:
- behavior: merge
  literals:
  - enable_graphiql="false"
  - enable_graphql_introspection="true"
  - ixgyohn.baseUrl="https://images.otomadb.com"
  name: api-configmap
images:
- name: graphql-api
  newName: ghcr.io/otomadb/graphql-api
  digest: sha256:d2832082bf8302601ab113fa7ac3074a11652e0b6d22ad34304438db060c9e1d
- name: postgres-migration
  newName: ghcr.io/otomadb/api-postgres-migration
  newTag: 20231214201404_nicovideo_video_source_registeredat
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
- name: nicovideo-updater
  newName: ghcr.io/otomadb/nicovideo-updater
  digest: sha256:e496690c47eb7b9f3c3d1e23c9b88a50fddbab2a12f5c3610db78f8ef48466e3
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/env: prod
    app.kubernetes.io/managed-by: kustomize
