apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
- ./secrets.enc.yaml
configMapGenerator:
- behavior: merge
  literals:
  - enable_graphiql="false"
  - enable_graphql_introspection="true"
  name: api-configmap
images:
- name: graphql-api
  newName: ghcr.io/otomadb/graphql-api
  digest: sha256:74410c475b4720c9c02fd86e63d1b8b47e6dfc738ca2e111b7d4cf3102aba1be
- name: postgres-migration
  newName: ghcr.io/otomadb/postgres-migration
  newTag: 20231219184638_video_title_id
- name: meilisearch-syncer
  newName: ghcr.io/otomadb/meilisearch-syncer
  digest: sha256:a4f6946a6d58ac027b1795ebb98a65e8eb304260636ba9eb9d45da7e45177b65
- name: neo4j-syncer
  newName: ghcr.io/otomadb/neo4j-syncer
  digest: sha256:464a4dd88d281fc8fdf79f909fcda6349a3cde44f04d5f447c8a522723851025
- name: nicovideo-updater
  newName: ghcr.io/otomadb/nicovideo-updater
  digest: sha256:cc59c663145e620d5088a9a4eb9bdaca52d4fbb0efc5769db30d878ee969f172
- name: ixgyohn
  newName: ghcr.io/otomadb/ixgyohn
  digest: sha256:52ef0b5567daadef49bb6b1a10848148383bf86e82b5793bb3e9791909e96319
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/env: prod
    app.kubernetes.io/managed-by: kustomize
