apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otomadb-api
  annotations:
    # argocd-image-updater.argoproj.io/argocd.force-update: true
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: |
      api=ghcr.io/otomadb/api:latest,
      meilisearch-syncer=ghcr.io/otomadb/meilisearch-syncer:latest,
      neo4j-syncer=ghcr.io/otomadb/neo4j-syncer:latest
    # ,api-postgres-migration=ghcr.io/otomadb/api-postgres-migration:latest
    # api
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/api.kustomize.image-name: api
    # api-postgres-migration
    # argocd-image-updater.argoproj.io/api-postgres-migration.update-strategy: digest
    # argocd-image-updater.argoproj.io/api-postgres-migration.kustomize.image-name: api-postgres-migration
    argocd-image-updater.argoproj.io/meilisearch-syncer.update-strategy: digest
    argocd-image-updater.argoproj.io/meilisearch-syncer.kustomize.image-name: meilisearch-syncer
    argocd-image-updater.argoproj.io/neo4j-syncer.update-strategy: digest
    argocd-image-updater.argoproj.io/neo4j-syncer.kustomize.image-name: neo4j-syncer
spec:
  project: prev-otomadb
  source:
    repoURL: https://github.com/otomadb/k8s-manifests
    targetRevision: main
    path: api/overlays/prev
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prev-otomadb
