apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otomadb
spec:
  description: otomadb for Preview Environment
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: prev-otomadb
  sourceRepos:
    - git@github.com:otomad-database/k8s-manifests.git
    - https://charts.bitnami.com/bitnami
    - https://bitnami-labs.github.io/sealed-secrets
    - https://neo4j.github.io/helm-charts
