apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.yaml
  - ./meilisearch-syncer.yaml
  - ./neo4j-syncer.yaml
  - ./nicochuu.yaml
configMapGenerator:
  - name: api-configmap
