apiVersion: batch/v1
kind: CronJob
metadata:
  name: meilisearch-syncer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: meilisearch-syncer
              image: meilisearch-syncer
              imagePullPolicy: IfNotPresent
              ttlSecondsAfterFinished: 3600
              env:
                - name: POSTGRES_URL
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: postgres.url
                - name: MEILISEARCH_URL
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: meilisearch.url
