apiVersion: batch/v1
kind: CronJob
metadata:
  name: neo4j-syncer
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: neo4j-syncer
              image: neo4j-syncer
              imagePullPolicy: IfNotPresent
              ttlSecondsAfterFinished: 3600
              env:
                - name: POSTGRES_URL
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: postgres.url
                - name: NEO4J_BOLT_URL
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: neo4j.url
                - name: NEO4J_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: neo4j.username
                - name: NEO4J_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: neo4j.password
