apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nicochuu-postgres
spec:
  selector:
    matchLabels:
      app: nicochuu-postgres
  serviceName: nicochuu-postgres
  template:
    metadata:
      labels:
        app: nicochuu-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_DB
              value: test
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nicochuu-postgres
  labels:
    app: nicochuu-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: nicochuu-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicochuu
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nicochuu
  template:
    metadata:
      labels:
        app: nicochuu
    spec:
      initContainers:
        - name: migration
          image: ghcr.io/otomadb/nicochuu-migration:1.0.0-rc.1
          env:
            - name: DATABASE_URL
              value: postgresql://user:pass@nicochuu-postgres:5432/test
      containers:
        - name: nicochuu
          image: ghcr.io/otomadb/nicochuu:1.0.0-rc.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 58080
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
          env:
            - name: SCRAPE_INTERVAL
              value: "600"
            - name: SCRAPE_DURATION
              value: "172800"
            - name: SCRAPE_TAGS
              value: "音MAD"
            - name: DATABASE_URL
              value: postgresql://user:pass@nicochuu-postgres:5432/test
---
apiVersion: v1
kind: Service
metadata:
  name: nicochuu
spec:
  type: NodePort
  ports:
    - port: 58080
  selector:
    app: nicochuu
