apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
spec:
  completions: 1
  parallelism: 1
  backOffLimit: 2
  template:
    spec:
      containers:
        - name: postgres-migration
          image: postgres-migration
          imagePullPolicy: IfNotPresent
          env:
            - name: PRISMA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: postgres.url
              restartPolicy: Never
