apiVersion: v1
kind: Service
metadata:
  name: ixgyohn
spec:
  type: ClusterIP
  selector:
    app: ixgyohn
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 1323
    - name: imgproxy
      protocol: TCP
      port: 80
      targetPort: 8080
