apiVersion: v1
kind: Secret
metadata:
    name: api-secret
type: Opaque
stringData:
    PRISMA_DATABASE_URL: ENC[AES256_GCM,data:wkmHm/M8RXWI5dV+oY6EXoOEvh/O0LGwwQUCFfJCjUvEPFzdCBhlSukc04vY5MTW/1mPOcpv,iv:prSS06+wleakvXKjAtn7yqs8N8pWppKywNdctVfzklc=,tag:3Dhnfi5EEeT9S41QJkAzoQ==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:8avPNNfPmUxzl7R5hXvCkhyzxT3v4sjkNfD+MRoX1ZNwrxdy2glea1q7skq1/WvpuUYskAqm,iv:a2374JNdpPDuF+ExXzhj2fWsBVJR+kYU4FVNjn1KHqw=,tag:29ORmOZ0nCsjihXwVp46ww==,type:str]
    MEILISEARCH_URL: ENC[AES256_GCM,data:sfYvbITkN8gGXCAM3YPuaEymVQSDKnw=,iv:wawiCqC6xzOUj5aeApBHdbiFupt9NMySSa6u71QsU2E=,tag:IeEYqORPkBt2ek5aXBgYRA==,type:str]
    NEO4J_URL: ENC[AES256_GCM,data:Rv0KSU6Hi7nmJodAy5ZVti0=,iv:72Nlv6AA85qFhTcVmxeWv9uRO3Oc5iZvTcE6ixnIM1Y=,tag:oexZCIaeux3nHSKBGWqP/A==,type:str]
    NEO4J_USERNAME: ENC[AES256_GCM,data:IrpmpUs=,iv:de4rYjkSbPswvOayuQPQoLkI+tbxt1mcrsZKwplgmvE=,tag:FwgBvXIVxXe7S2Sa0DojGw==,type:str]
    NEO4J_PASSWORD: ENC[AES256_GCM,data:NnkYXhSQxxwTxUV4Kao=,iv:ReC3NbzVEazwDDbhyWf9aV6IlbB8J6/bn9fR/l5qZjk=,tag:XRyDq3MZO6C3YIcxlrT9hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-22T15:41:32Z"
    mac: ENC[AES256_GCM,data:JMCKqZTMl/U+Q9ICIiCb3Wc5MC9/3G6FCqp/Xlh+9bWshz4NoFPFDNuUGjxxXGYS4ufJeXTdYSZwQb6eQv5+je/x4/8J36uCzN0HbMISXNupPht7IBcM7+/AGtp+cUgwJukTTGwdeU6Ej9wYsZwS3FeCIa0Hyw5TEdZuorJ2NUc=,iv:9E2cZ+nTeKGryNf08rIgSRj6fAei9w7ArCVv6ae/Sew=,tag:eR6sH/Kg74ZllgQYvG1VgA==,type:str]
    pgp:
        - created_at: "2023-03-22T15:41:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyadMEQU/CnhARAAluD9lmBzpKOXTaS1CxeYqr5BSmLO7DG0TkRDqHwxFBVE
            zDpnngjJGRiUX8cCHrBGdKz6I4O389FjJW3AS5GY8BABUUr74GPEW+JlwQX6iFyk
            bRizBHNk2Qw70NrgxTGRkuFGQZldcgEHPFm/BcU6HBRxSY55sjK36tYrR4c3QLhH
            U+K05tX9KmrLJSz2wiqVjohr4cpMretPMeGhOz52sMzOPRg95AS1rQN0WA5QenC4
            EikznH21EDQYxWmcZzuJJ3DHx7axVLS9mdz74hafAmE8eqFtPMcL7ZkZRPIoSRPw
            v8I9xFttlyMjj3xnHyR2GP1iuMvw/4/ePEg+Bd+N1YfG/pcLHBlv9uA65bG6HFKR
            lm8D0NlvUXsIB+NBEc7t7Hqpl9nVC68S+Bwi7tKTIC5C9drtMr9nf8zND5XSc0NY
            68w7t4RFgHoL/UHZnVsQToagZMOoAwLLJRX4C6ujyneh9RALEEkTB5C1+Os5rvG3
            yNbWNphJaa7s4Fuial9F+HlPaWseI2pXdPieGDUmEU4Q2g+im9yvsmXfzWXok6PQ
            C4FXYnTZBDuZDNCHegjW1dWrPYPMNLED26B1sjlmsUOql1Tgv0/LkLgGFKUPHFAj
            Vnv8njpIX769oPSuO7DXfSM5zZG5PsgfHBr/RtplmEGfTf34BKJfFXzDGwUmDQfU
            aAEJAhBt92JwnZ+0OV4QvbgKHSWIC3nfBqFfJUqa7dCUQAzLpk9BYVQ4LxoCpVat
            mhrcZM4X7MWBcQFtnae56XPjqCX5c2WrHIxrlQgU8FveBy9uUEZTO3ava7aP7Vj4
            ZBAetXiR5hAL
            =Yl1c
            -----END PGP MESSAGE-----
          fp: 4052669590974A212F67DBE4282792C188CFBA1F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
