apiVersion: viaduct.ai/v1
kind: KSOPSGenerator
metadata:
  name: ixgyohn-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../overlays/prod/secrets.enc.yaml
