apiVersion: v1
kind: Secret
metadata:
    name: ixgyohn-secret
type: Opaque
stringData:
    IMGPROXY_KEY: ENC[AES256_GCM,data:MevS+yBH5Y4ifGjT9YmoCqtuAakrrJMX7Y8wqzBBYm+U3awgj1O12yMKNr6OFwPYchF0rM3ZZW/p9Fb1DdaGRYznroa7xX+5QqEsExKt8hHfoGy0+OtqwsF8dh2r7T9M1pOdStrzxaWLQNXfv3EPVkV2Pt+tKyY7yb9igAQlXd8=,iv:aEUePKCFivpvuEim88hioNihleb1TYB/2TqJAcnv90E=,tag:LZWSdOtK93Mw1wRq0DuMFg==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:Kj59rdpJFywCTYTXf0yfvhDbvlIKuG5x78cfZVTlhjC5oJvxNTiQ6gPvnnKN1ND3DBqXzDlFIu0WC3sfnHw792wxIWpmAx+cItCWW/1xnOm7yoVJKQV3GRDXoq4AK6fyTADKFYLWr+Ieec0xgPQjqF7ZJNat/gxdSxMDd9AgjLE=,iv:r673ADJxVbLBegNDvSCtEf9erYp6KdfrUXyli93CJuQ=,tag:Ao5PTJbymq+eq1mtusx0fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-22T23:49:56Z"
    mac: ENC[AES256_GCM,data:LArvIdd/be/8oX6LedZx5tsdVj0iMPovRJWOaGJKegfxDtbIXOZjIftjdwylsZ5bKNUwMOxtvIdObVvxD/lJuRLgIDfEoEJITQgeHSkCn5DOAabC6TUw04CD2ZcoA56NhDlhq3ZpBB9H3xsSV8eyQaiqPJtoMtwfmGb/AIPq8vg=,iv:ljRaAvYP6+Dn3WYcX76QLcXQO7eJll/5sl3p7DBl4IQ=,tag:zZp+eHhcBl4OIZHPP2vizA==,type:str]
    pgp:
        - created_at: "2023-09-22T23:49:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyadMEQU/CnhAQ//dct8VAH3SPtMJhgcVj27VK7cSh+mHo3T/lalHgygDCSW
            9k7uuRdsJIShbIdXYsf1kTR9H3LBD0Rs8ysS8Jk31W0EQZOYf+zQwvlyjoQIZWaq
            Qb9RiEFPJznFkgPl4G4XIMXxg/hWIBbhN144Gk/iRD39nNPG/zHiPgBFVfPb7MIo
            AeuxMNk2MdHGehPD/2W+BU3L426WFTet81UrJHteKkoeK6x691MgVeR1b+DCsZ7D
            6Tx0lZsO5T+5k5aKo06liDJBeVJBmg4RNfds6vPjCukQSzUZQ4ShbVeBltv+QCou
            2jp3tuUp7xRlq3oKdDtplFLZNCKMa3+XNrADzmCTcGRYNArar8frJSoTmmlHmV1I
            ZMmlWGON7ZPczEPAVjRoaPkaD+XB0Koax0E8GickptMZ68pA1mzIfoYjLY7gDQmM
            N13dlm69c9L3VWojh7Q8T/g41BDIcDQ2PnAo2ih2SwkxZzXdewBYG8jH4JPZNJ5q
            kd3QoNzgX3QuQXR+Wa4gX71UZsOsW/iXOZwelT37BfwypRPElG58VE+ayyFPXxrc
            ozNKlHXhTV5RNdZ4OwGC6b7+ESakjHtZ9dSyJq6tciSL/hDZ1wlyIXIHPnvgy++Z
            +HD1TafyHXEfMBevm6nqNliUB7a1HRZP+uNxO37sOz/kRf4H22VYkfGWBWs+paDU
            aAEJAhC2Bqt9yOLXraye4eAQQBE/aXDILD0yk5QX/reXhyBr1UGESQf4sEb22PWL
            Omii612F75R3Hu1MsF+XPV1gbf5UHpZaw38ao4d2L4h7++7uvRHw2L6OcDRNbFUT
            W0Rx+KW5mlRf
            =hy8A
            -----END PGP MESSAGE-----
          fp: 4052669590974A212F67DBE4282792C188CFBA1F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
