apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otomadb-api
  annotations:
    # argocd-image-updater.argoproj.io/argocd.force-update: true
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: |
      graphql-api=ghcr.io/otomadb/graphql-api:latest,
      postgres-migration=ghcr.io/otomadb/api-postgres-migration,
      meilisearch-syncer=ghcr.io/otomadb/meilisearch-syncer:latest,
      neo4j-syncer=ghcr.io/otomadb/neo4j-syncer:latest
    # graphql-api
    argocd-image-updater.argoproj.io/graphql-api.update-strategy: digest
    argocd-image-updater.argoproj.io/graphql-api.kustomize.image-name: graphql-api
    # postgres-migration
    argocd-image-updater.argoproj.io/postgres-migration.update-strategy: latest
    argocd-image-updater.argoproj.io/postgres-migration.kustomize.image-name: postgres-migration
    # meilisearch syncer
    argocd-image-updater.argoproj.io/meilisearch-syncer.update-strategy: digest
    argocd-image-updater.argoproj.io/meilisearch-syncer.kustomize.image-name: meilisearch-syncer
    # neo4j syncer
    argocd-image-updater.argoproj.io/neo4j-syncer.update-strategy: digest
    argocd-image-updater.argoproj.io/neo4j-syncer.kustomize.image-name: neo4j-syncer
spec:
  project: prod-otomadb
  source:
    repoURL: https://github.com/otomadb/k8s-manifests
    targetRevision: main
    path: api/prod
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-otomadb
