apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otomadb
spec:
  description: OtoMADB for Production Environment
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: prod-otomadb
  sourceRepos:
    - https://github.com/otomadb/k8s-manifests
    - https://charts.bitnami.com/bitnami
    - https://neo4j.github.io/helm-charts
    - https://meilisearch.github.io/meilisearch-kubernetes
    - https://helm.imgproxy.net
    - https://bitnami-labs.github.io/sealed-secrets
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
