apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otomadb
spec:
  description: otomadb for Production Environment
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: prod-otomadb
  sourceRepos:
    - git@github.com:otomadb/k8s-manifests.git
    - https://charts.bitnami.com/bitnami
    - https://neo4j.github.io/helm-charts
    - https://meilisearch.github.io/meilisearch-kubernetes
