apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: otomadb-imgproxy
spec:
  project: prod-otomadb
  sources:
    - ref: valuesrepo
      repoURL: https://github.com/otomadb/helm-values
    - chart: imgproxy
      repoURL: https://helm.imgproxy.net
      targetRevision: 0.8.35
      helm:
        releaseName: imgproxy
        valueFiles:
          - $valuesrepo/prod/imgproxy/values.yaml
        valuesObject:
          resources:
            ingress:
              enabled: true
              className: nginx
              hosts:
                - imgproxy.otomadb.com
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-otomadb
