apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otomadb-ixgyohn
  annotations:
    # argocd-image-updater.argoproj.io/argocd.force-update: true
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: |
      ixgyohn=ghcr.io/otomadb/ixgyohn:latest
    argocd-image-updater.argoproj.io/ixgyohn.update-strategy: digest
    argocd-image-updater.argoproj.io/ixgyohn.kustomize.image-name: ixgyohn
spec:
  project: prod-otomadb
  source:
    repoURL: https://github.com/otomadb/k8s-manifests
    targetRevision: main
    path: ixgyohn/overlays/prod
    kustomize: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-otomadb
