apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: otomadb-meilisearch
spec:
  project: prod-otomadb
  source:
    chart: meilisearch
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    targetRevision: 0.1.49
    helm:
      releaseName: meilisearch
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-otomadb
