apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: otomadb-sealed-secrets
spec:
  project: prod-otomadb
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: "2.13.0"
    helm:
      releaseName: sealed-secrets
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-otomadb
